# Разбиение MicroLens-100K на train / validation / test

Цель этапа — произвести корректное разбиение данных: взаимодействия
пользователей с объектами на обучающую, валидационную и тестовую части.

При разбиении необходимо:

- сохранить временной порядок взаимодействий;
- предотвратить утечку информации из будущего;
- сохранить достаточную историю пользователей в обучающей выборке;
- определить поведение для объектов, отсутствующих в обучающей выборке.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [3]:
data_path = Path("../../data/raw/microlens")
interactions_path = data_path / "MicroLens-100k_pairs.csv"
interactions_df = pd.read_csv(interactions_path)
interactions_df.head(10)

    user  item      timestamp
0  36121  9580  1583378629552
1  26572  9580  1583436719018
2  94805  9580  1584083806481
3  37550  9580  1584412681021
4  89825  9580  1584649439020
5  14601  9580  1584848802432
6  15061  9580  1585388171106
7   6364  9580  1585390736041
8  99661  9580  1585392581153
9  57849  9580  1585394954324

In [4]:
interactions_df["datetime"] = pd.to_datetime(interactions_df["timestamp"], unit="ms")

In [6]:
interactions_df = interactions_df.sort_values(["user", "timestamp"]).reset_index(drop=True)
interactions_df.head(10)

   user   item      timestamp                datetime
0     1   1958  1648809472482 2022-04-01 10:37:52.482
1     1   6346  1654693851331 2022-06-08 13:10:51.331
2     1  15223  1658056684232 2022-07-17 11:18:04.232
3     1  17700  1658663077653 2022-07-24 11:44:37.653
4     1   1707  1660215530977 2022-08-11 10:58:50.977
5     2  16657  1653002079551 2022-05-19 23:14:39.551
6     2    915  1654949021395 2022-06-11 12:03:41.395
7     2   9127  1657546790850 2022-07-11 13:39:50.850
8     2   3775  1657722544814 2022-07-13 14:29:04.814
9     2   9500  1657754015460 2022-07-13 23:13:35.460

Посмотрим разделение для 1 пользователя:

In [7]:
user_id = 1
user_history = interactions_df[interactions_df["user"] == user_id]
user_history

   user   item      timestamp                datetime
0     1   1958  1648809472482 2022-04-01 10:37:52.482
1     1   6346  1654693851331 2022-06-08 13:10:51.331
2     1  15223  1658056684232 2022-07-17 11:18:04.232
3     1  17700  1658663077653 2022-07-24 11:44:37.653
4     1   1707  1660215530977 2022-08-11 10:58:50.977